site_name: Visual Scripting Addon
theme: 'readthedocs'
markdown_extensions:
  - admonition


nav:
  - Introduction: getting_started/index.md

  - For developers:
    - Introduction: developers/index.md
    - Project Setup: developers/setup.md
    - Creating Categories: developers/categories.md
    - Creating Nodes: developers/nodes.md
    - Distributing: developers/distributing.md