site_name: Serpens - Visual Scripting Addon
theme: 'readthedocs'
markdown_extensions:
  - admonition
  - attr_list


nav:
  - Introduction: index.md

  - Documentation:
    - Getting Started: developers/getting_started.md
    - Creating A Node: developers/create_node.md
    - Socket Handler: developers/socket_handler.md
    - Distribution: developers/distribution.md