site_name: Serpens - Visual Scripting Addon
theme: readthedocs
markdown_extensions:
  - admonition
  - attr_list


nav:
  - Introduction: index.md

  - Getting Started:
    - Basics: developers/getting_started.md
    - Setup: developers/setup.md
  - Nodes:
    - Basics: developers/nodes.md
    - Node Options: developers/node_options.md
    - Sockets: developers/node_sockets.md
    - Events: developers/node_events.md
    - Draw Node: developers/node_draw.md
    - Generating Code: developers/node_code.md
    - Node Functions: developers/node_functions.md
  - Distribution:
    - Distribution: developers/distribution.md